version: "2"
services:
  pkg_sender:
    build: .
    container_name: pkg_sender
    volumes:
      - /mnt/media/Games/PS4:/opt/apps/pkg_sender/files
    ports:
      - 3333:8080
    environment:
      - PORT=8080
      - STATIC_FILES=/opt/apps/pkg_sender/files
      - LOCALIP=192.168.10.245
      - PS4IP=192.168.10.150
    restart: unless-stopped
